server:
  port: 10010

spring:
  application:
    name: zb-gateway
  cloud:
    refresh:
      refreshable: none  #不加入会造成循环依赖?

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true

zuul:
  prefix: /api # 添加路由前缀